# We explicitly prepend config for "ezpublish" namespace in service container extension,
# so no need to repeat it here
system:
    ezdemo_site:
        location_view:
            full:
                article_test:
                    template: "CjwCookBookBundle:full:article.html.twig"
                    match:
                        Identifier\ContentType: article
        field_templates:
            -
                template: "CjwCookBookBundle:fields:field_templates.html.twig"
                # Priority is optional (default is 0). The higher it is, the higher your template gets in the list.
                priority: 10
    eng:
        location_view:
            full:
                article_test:
                    template: "CjwCookBookBundle:full:article.html.twig"
                    match:
                        Identifier\ContentType: article
        field_templates:
            -
                template: "CjwCookBookBundle:fields:field_templates.html.twig"
                # Priority is optional (default is 0). The higher it is, the higher your template gets in the list.
                priority: 10
