parameters:
#    cjw_cook_book.example.class: CjwNetwork\SummerCamp2013\CookBookBundle\Example

services:
#    cjw_cook_book.example:
#        class: %cjw_cook_book.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
